feat(CAPI): :sparkles: update with new rules
eesast/THUAI6 pull request #146
Opened 2023-03-16 02:47 UTC by DragonAura

- [ ] 您的代码是否能够编译通过？
- [ ] 您是否检查了目前在 [pull requests](https://github.com/eesast/THUAI6/pulls) 中是否有与你的贡献功能相同的更改？
- [ ] 您的贡献是否符合[贡献者代码协议](https://github.com/eesast/THUAI6/blob/dev/CODE_OF_CONDUCT.md)？
- [ ] 您的贡献是否符合[开发规则](https://github.com/eesast/THUAI6#%E5%BC%80%E5%8F%91%E8%A7%84%E5%88%99)？  

Descriptions of this pull request:

No additional discription.

2023-03-16 15:45 UTC, Timothy-Liuxf requested changes
加 `[[nodiscard]]` 防止误调用

2023-03-16 15:45 UTC, Timothy-Liuxf commented on CAPI/cpp/API/include/API.h
> +    virtual std::shared_ptr<const THUAI6::GameInfo> GetGameInfo() const = 0;
```suggestion
    [[nodiscard]] virtual std::shared_ptr<const THUAI6::GameInfo> GetGameInfo() const = 0;
```

此处以上所有 `Get` 函数都加上 `[[nodiscard]]` 吧

2023-03-16 15:49 UTC, Timothy-Liuxf commented on CAPI/cpp/API/src/logic.cpp
> +bool Logic::IsDoorOpen(int32_t CellX, int32_t CellY) const
```suggestion
bool Logic::IsDoorOpen(int32_t cellX, int32_t cellY) const
```

2023-03-16 15:49 UTC, Timothy-Liuxf commented on CAPI/cpp/API/src/logic.cpp
> +int32_t Logic::GetClassroomProgress(int32_t CellX, int32_t CellY) const
```suggestion
int32_t Logic::GetClassroomProgress(int32_t cellX, int32_t cellY) const
```

2023-03-17 13:23 UTC, Timothy-Liuxf requested changes

2023-03-18 13:44 UTC, TCL606 approved these changes

2023-03-18 15:04 UTC, Timothy-Liuxf approved these changes

2023-03-18 15:05 UTC, merged