fix: :bug: fix the communication of TimeUntilSkillAvailable
eesast/THUAI6 pull request #160
Opened 2023-03-21 17:16 UTC by shangfengh

In the MessageOfStudent,TimeUntilSkillAvailable have -1 meaning null

  

- [x] 您的代码是否能够编译通过？
- [x] 您是否检查了目前在 [pull requests](https://github.com/eesast/THUAI6/pulls) 中是否有与你的贡献功能相同的更改？
- [x] 您的贡献是否符合[贡献者代码协议](https://github.com/eesast/THUAI6/blob/dev/CODE_OF_CONDUCT.md)？
- [x] 您的贡献是否符合[开发规则](https://github.com/eesast/THUAI6#%E5%BC%80%E5%8F%91%E8%A7%84%E5%88%99)？  

Descriptions of this pull request:

No additional discription.

2023-03-21 17:38 UTC, Timothy-Liuxf requested changes
之前的 format checking 的 ci 有点问题，拉取一下最新的 ci，并且 format 一下

2023-03-21 17:42 UTC, Timothy-Liuxf requested changes

2023-03-21 17:42 UTC, Timothy-Liuxf commented on logic/Server/CopyInfo.cs
>              foreach (var Value in player.PropInventory)
```suggestion
            foreach (var value in player.PropInventory)
```

2023-03-21 18:11 UTC, Timothy-Liuxf approved these changes

2023-03-21 18:13 UTC, Timothy-Liuxf commented
Resolve 掉 conversations

2023-03-21 18:28 UTC, shangfengh commented
> Resolve 掉 conversations

I fail to comprehend the sentence.

2023-03-22 04:33 UTC, Timothy-Liuxf approved these changes

2023-03-22 04:33 UTC, merged