fix: 💚 fix CI
eesast/THUAI6 pull request #341
Opened 2023-04-20 14:47 UTC by shangfengh

- [ ] 您的代码是否能够编译通过？
- [ ] 您是否检查了目前在 [pull requests](https://github.com/eesast/THUAI6/pulls) 中是否有与你的贡献功能相同的更改？
- [ ] 您的贡献是否符合[贡献者代码协议](https://github.com/eesast/THUAI6/blob/dev/CODE_OF_CONDUCT.md)？
- [ ] 您的贡献是否符合[开发规则](https://github.com/eesast/THUAI6#%E5%BC%80%E5%8F%91%E8%A7%84%E5%88%99)？  

Descriptions of this pull request:

No additional discription.

2023-04-20 14:48 UTC, Timothy-Liuxf submitted a review, later dismissed

2023-04-20 14:49 UTC, OctaAcid submitted a review, later dismissed

2023-04-20 14:50 UTC, TCL606 approved these changes

2023-04-20 16:01 UTC, TCL606 approved these changes

2023-04-20 17:58 UTC, Timothy-Liuxf approved these changes

2023-04-20 17:58 UTC, Timothy-Liuxf requested changes

2023-04-20 17:58 UTC, Timothy-Liuxf commented on .github/workflows/upload_COS.yml
> +    - name: Unix to docs
```suggestion
    - name: Unix to DOS
```

2023-04-21 01:39 UTC, TCL606 approved these changes

2023-04-21 01:39 UTC, merged